/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project.home;

import Project.admin.AdminLogin;
import Project.student.StudentLogin;
import Project.librarian.LibrarianLogin;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ALEX STORE
 */
public class UserOptions extends javax.swing.JFrame {

    /**
     * Creates new form UserOptions
     */
    public UserOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LibrarianClassDirect = new javax.swing.JButton();
        AdminClassDirect = new javax.swing.JButton();
        Studentlogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Library Managment");

        LibrarianClassDirect.setBackground(new java.awt.Color(0, 153, 255));
        LibrarianClassDirect.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LibrarianClassDirect.setText("Librarian Login");
        LibrarianClassDirect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrarianClassDirectActionPerformed(evt);
            }
        });

        AdminClassDirect.setBackground(new java.awt.Color(0, 153, 255));
        AdminClassDirect.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        AdminClassDirect.setText("Admin Login");
        AdminClassDirect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminClassDirectActionPerformed(evt);
            }
        });

        Studentlogin.setBackground(new java.awt.Color(0, 153, 255));
        Studentlogin.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Studentlogin.setText("Student Login");
        Studentlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LibrarianClassDirect, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminClassDirect, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Studentlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(AdminClassDirect, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(LibrarianClassDirect, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Studentlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminClassDirectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminClassDirectActionPerformed
        // TODO add your handling code here:
       AdminLogin f = new AdminLogin();
                f.setVisible(true);
                this.hide();
        
    }//GEN-LAST:event_AdminClassDirectActionPerformed

    private void LibrarianClassDirectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrarianClassDirectActionPerformed
        // TODO add your handling code here:
        LibrarianLogin l = null;
        l = new LibrarianLogin();
        l.setVisible(true);
        this.hide();
    }//GEN-LAST:event_LibrarianClassDirectActionPerformed

    private void StudentloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentloginActionPerformed
        // TODO add your handling code here:
          StudentLogin f = null;
          f = new StudentLogin();
                f.setVisible(true);
                this.hide();
        
                                 
    }//GEN-LAST:event_StudentloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserOptions().setVisible(true);
                
                
                
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminClassDirect;
    private javax.swing.JButton LibrarianClassDirect;
    private javax.swing.JButton Studentlogin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
